language: go

go:
  - 1.9

install:
  - go get ./...

before_script:
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - go vet
  - go fmt ./...
  - $GOPATH/bin/golint ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
