language: go

go:
  - 1.9

install:
  - go get ./...

before_script:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/mattn/goveralls

script:
  - go fmt ./...
  - $GOPATH/bin/golint ./...

after_script:
  - $GOPATH/bin/goveralls -service=travis-pro
