version: 2

jobs:
  build:
    docker:
      - image: cn007b/go:1.10

    working_directory: /go/src/github.com/thepkg/strings

    steps:
      - checkout

     - run: go get -v -t -d ./...
     - run: go get -u golang.org/x/lint/golint
     - run: go get -u github.com/mattn/goveralls

     - run: go vet
     - run: go fmt ./...
     - run: /go/src/github.com/thepkg/strings/bin/golint ./...

     - run: go test -v ./...
     - run: /go/src/github.com/thepkg/strings/bin/goveralls -service=travis-pro
